"""Initial migration.

Revision ID: ff430c00a2a5
Revises: 
Create Date: 2021-06-13 01:06:12.119230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff430c00a2a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('duree', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('Niveau', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'Niveau')
    op.drop_column('question', 'duree')
    # ### end Alembic commands ###
